name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Deploy
        working-directory: ./packages/docs
        run: yarn deploy-storybook -- --ci --host-token-env-variable=GITHUB_TOKEN --existing-output-dir=storybook-static
